apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  name: ${cluster-name}
spec:
  cloudConfig:
    disableSecurityGroupIngress: true
  api:
    loadBalancer:
      type: ${master-lb-visibility}
      idleTimeoutSeconds: ${master-lb-idle-timeout}
  authorization:
    alwaysAllow: {}
  channel: ${channel}
  cloudLabels:
${cloud-labels}
  cloudProvider: aws
  clusterDNSDomain: ${cluster-name}
  configBase: s3://${kops-state-bucket}/${cluster-name}
  configStore: s3://${kops-state-bucket}/${cluster-name}
  dnsZone: ${cluster-name}
  docker:
    bridge: ''
    ipMasq: false
    ipTables: false
    logDriver: json-file
    logLevel: warn
    logOpt:
    - max-size=10m
    - max-file=5
    storage: overlay,aufs
    version: 1.12.6
  etcdClusters:
${etcd-clusters}
  keyStore: s3://${kops-state-bucket}/${cluster-name}/pki
  kubeAPIServer:
    address: 127.0.0.1
    admissionControl:
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - ResourceQuota
    allowPrivileged: true
    anonymousAuth: false
    apiServerCount: ${master-count}
    authorizationMode: AlwaysAllow
    cloudProvider: aws
    etcdServers:
    - http://127.0.0.1:4001
    etcdServersOverrides:
    - /events#http://127.0.0.1:4002
    image: gcr.io/google_containers/kube-apiserver:${kubernetes-version}
    insecurePort: 8080
    kubeletPreferredAddressTypes:
    - InternalIP
    - Hostname
    - ExternalIP
    logLevel: 2
    securePort: 443
    serviceClusterIPRange: 100.64.0.0/13
    storageBackend: etcd2
  kubeControllerManager:
    allocateNodeCIDRs: true
    attachDetachReconcileSyncPeriod: 1m0s
    cloudProvider: aws
    clusterCIDR: 100.96.0.0/11
    clusterName: ${cluster-name}
    configureCloudRoutes: false
    image: gcr.io/google_containers/kube-controller-manager:${kubernetes-version}
    leaderElection:
      leaderElect: true
    logLevel: 2
    useServiceAccountCredentials: true
  kubeDNS:
    domain: ${kube-dns-domain}
    image: gcr.io/google_containers/kubedns-amd64:1.3
    replicas: 2
    serverIP: 100.64.0.10
  kubeProxy:
    clusterCIDR: 100.96.0.0/11
    cpuRequest: 100m
    hostnameOverride: '@aws'
    image: gcr.io/google_containers/kube-proxy:${kubernetes-version}
    logLevel: 2
  kubeScheduler:
    image: gcr.io/google_containers/kube-scheduler:${kubernetes-version}
    leaderElection:
      leaderElect: true
    logLevel: 2
  kubelet:
    allowPrivileged: true
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: ${kube-dns-domain}
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: gcr.io/google_containers/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
    requireKubeconfig: true
  kubernetesApiAccess:
${trusted-cidrs}
  kubernetesVersion: ${kubernetes-version}
  masterInternalName: api.internal.${cluster-name}
  masterKubelet:
    allowPrivileged: true
    cgroupRoot: /
    cloudProvider: aws
    clusterDNS: 100.64.0.10
    clusterDomain: ${kube-dns-domain}
    enableDebuggingHandlers: true
    evictionHard: memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
    hostnameOverride: '@aws'
    kubeconfigPath: /var/lib/kubelet/kubeconfig
    logLevel: 2
    networkPluginName: cni
    nonMasqueradeCIDR: 100.64.0.0/10
    podInfraContainerImage: gcr.io/google_containers/pause-amd64:3.0
    podManifestPath: /etc/kubernetes/manifests
    registerSchedulable: false
    requireKubeconfig: true
  masterPublicName: api.${cluster-name}
  networkCIDR: ${vpc-cidr}
  networkID: ${vpc-id}
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  secretStore: s3://${kops-state-bucket}/${cluster-name}/secrets
  serviceClusterIPRange: 100.64.0.0/13
  sshAccess:
${trusted-cidrs}
  subnets:
${subnets}
  topology:
    bastion:
      bastionPublicName: bastion.${cluster-name}
    dns:
      type: ${master-lb-visibility}
    masters: private
    nodes: private
